export const brandColors = {
  primary: "#1a365d", // Navy blue from the logo
  primaryLight: "#2d4a6b",
  accent: "#e53e3e", // Red accent from the logo
  white: "#ffffff",
  lightGray: "#f7fafc",
  mediumGray: "#e2e8f0",
  darkGray: "#2d3748",
  textGray: "#718096",
  navy: "#1a365d",
  navyLight: "#2c5282",
  red: "#e53e3e",
}

export const themeConfig = {
  light: {
    background: brandColors.white,
    foreground: brandColors.navy,
    card: brandColors.white,
    cardForeground: brandColors.navy,
    popover: brandColors.white,
    popoverForeground: brandColors.navy,
    primary: brandColors.navy,
    primaryForeground: brandColors.white,
    secondary: brandColors.lightGray,
    secondaryForeground: brandColors.navy,
    muted: brandColors.lightGray,
    mutedForeground: brandColors.textGray,
    accent: brandColors.red,
    accentForeground: brandColors.white,
    destructive: brandColors.red,
    destructiveForeground: brandColors.white,
    border: brandColors.mediumGray,
    input: brandColors.mediumGray,
    ring: brandColors.navy,
  },
  dark: {
    background: brandColors.darkGray,
    foreground: brandColors.white,
    card: "#2a2d3a",
    cardForeground: brandColors.white,
    popover: "#2a2d3a",
    popoverForeground: brandColors.white,
    primary: brandColors.navyLight,
    primaryForeground: brandColors.white,
    secondary: "#3f3f46",
    secondaryForeground: brandColors.white,
    muted: "#3f3f46",
    mutedForeground: brandColors.textGray,
    accent: brandColors.red,
    accentForeground: brandColors.white,
    destructive: brandColors.red,
    destructiveForeground: brandColors.white,
    border: "#3f3f46",
    input: "#3f3f46",
    ring: brandColors.navyLight,
  },
}
