export const brandColors = {
  primary: "#246bfd",
  white: "#ffffff",
  lightGray: "#f4f6f9",
  darkGray: "#1f2029",
  textGray: "#7c8091",
}

export const themeConfig = {
  light: {
    background: brandColors.white,
    foreground: brandColors.darkGray,
    card: brandColors.white,
    cardForeground: brandColors.darkGray,
    popover: brandColors.white,
    popoverForeground: brandColors.darkGray,
    primary: brandColors.primary,
    primaryForeground: brandColors.white,
    secondary: brandColors.lightGray,
    secondaryForeground: brandColors.darkGray,
    muted: brandColors.lightGray,
    mutedForeground: brandColors.textGray,
    accent: brandColors.lightGray,
    accentForeground: brandColors.darkGray,
    destructive: "#ef4444",
    destructiveForeground: brandColors.white,
    border: "#e2e8f0",
    input: "#e2e8f0",
    ring: brandColors.primary,
  },
  dark: {
    background: brandColors.darkGray,
    foreground: brandColors.white,
    card: "#2a2d3a",
    cardForeground: brandColors.white,
    popover: "#2a2d3a",
    popoverForeground: brandColors.white,
    primary: brandColors.primary,
    primaryForeground: brandColors.white,
    secondary: "#3f3f46",
    secondaryForeground: brandColors.white,
    muted: "#3f3f46",
    mutedForeground: brandColors.textGray,
    accent: "#3f3f46",
    accentForeground: brandColors.white,
    destructive: "#ef4444",
    destructiveForeground: brandColors.white,
    border: "#3f3f46",
    input: "#3f3f46",
    ring: brandColors.primary,
  },
}
